# Generated by Django 4.0.4 on 2022-05-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus_housing_app', '0003_remove_subjects_staff_id_courses_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='off_campus_housing_app.staffs'),
        ),
    ]
