# Generated by Django 4.0.4 on 2022-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus_housing_app', '0004_alter_courses_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='staff_id',
            field=models.CharField(max_length=255),
        ),
    ]
