# Generated by Django 4.0.4 on 2022-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus_housing_app', '0009_alter_subjects_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
