# Generated by Django 4.0.4 on 2022-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus_housing_app', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='age',
            field=models.CharField(choices=[('O', 'Over 18'), ('U', 'No Preference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='bathroom',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Shared'), ('P', 'Private')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='category',
            field=models.CharField(choices=[('T', 'Two Bedrooms'), ('O', 'One Bedroom'), ('B', 'Bedsitters'), ('S', 'Single Rooms'), ('H', 'Hostel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='deposit_amount',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='electricity_charge',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='housemates',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='kitchen',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Shared'), ('P', 'Private')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='music',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('G', 'Negotiable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='per',
            field=models.CharField(choices=[('M', 'Month'), ('S', 'Semester')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='pets',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('G', 'Negotiable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='rental_cost',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='sex',
            field=models.CharField(choices=[('N', 'Male'), ('Y', 'Female'), ('G', 'No Preference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='smoking',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('G', 'Negotiable'), ('O', 'Outside The Premises')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='tenant_type',
            field=models.CharField(choices=[('N', 'Student'), ('Y', 'Working Professional'), ('G', 'No Preference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='toilet',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Shared'), ('P', 'Private')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='units',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='water_charge',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='subjects',
            name='wheelchair',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='wifi',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='wifi_charge',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
