# Generated by Django 4.0.4 on 2022-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus_housing_app', '0011_subjects_age_subjects_bathroom_subjects_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='bathroom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='housemates',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='kitchen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='music',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='per',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='pets',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='smoking',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='tenant_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='toilet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='wheelchair',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='wifi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
